version: '3.9'

services:
  isla_postgres:
    ports:
      - "5432:5432"
    image: postgres
    networks:
      isla_network:
        ipv4_address: 172.32.0.2
    restart: always
    environment:
      POSTGRES_USER: isla
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  aiguilleur:
    ports:
      - "8080:8080"
    image: isla_aiguilleur
    command: /bin/sh -c "sleep 3 && python3 app.py"
    networks:
      isla_network:
        ipv4_address: 172.32.0.3
    restart: always
    depends_on:
      - isla_postgres

  controleur_db:
    ports:
      - "8081:8081"
    image: isla_controleur_db
    command: /bin/sh -c "sleep 3 && python3 -m API"
    networks:
      isla_network:
        ipv4_address: 172.32.0.4
    restart: always
    depends_on:
      - aiguilleur

  choix:
    ports:
      - "8082:8082"
    image: isla_choix
    command: /bin/sh -c "sleep 3 && python3 app.py"
    networks:
      isla_network:
        ipv4_address: 172.32.0.5
    restart: always
    depends_on:
      - aiguilleur
      - controleur_db

networks:
  isla_network:
    external: true
