# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Choix - Install dependencies
      run: |
        cd ./choix
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Choix - Test with pytest
      run: |
        cd ./choix
        pytest ./app.py
    - name: Choix - Build the Docker image
      run:  |
        cd ./choix
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        echo "$DOCKER_PASSWORD" | docker build . --file Dockerfile --tag ethokia/isla-choix:$(date +'%d%m%y') --username "$DOCKER_USERNAME" --password-stdin
        echo "$DOCKER_PASSWORD" | docker push ethokia/isla-choix:$(date +'%d%m%y') --username "$DOCKER_USERNAME" --password-stdin
    - name: Aiguilleur - Install dependencies
      run: |
        cd ./aiguilleur
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Aiguilleur - Test with pytest
      run: |
        cd ./aiguilleur
        pytest ./app.py
    - name: Aiguilleur - Build the Docker image
      run:  |
        cd ./aiguilleur
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        echo "$DOCKER_PASSWORD" | docker build . --file Dockerfile --tag ethokia/isla-aiguilleur:$(date +'%d%m%y') --username "$DOCKER_USERNAME" --password-stdin
        echo "$DOCKER_PASSWORD" | docker push ethokia/isla-aiguilleur:$(date +'%d%m%y') --username "$DOCKER_USERNAME" --password-stdin
