# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python


name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Choix - Install dependencies
      run: |
        cd ./choix
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Choix - Test with pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cd ./choix
        pytest ./app.py
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Choix - Build the Docker image
      run:  |
        cd ./choix
        docker build . --file Dockerfile --tag gregorie/isla-choix:$(date +'%d%m%y')
        docker push gregorie/isla-choix:$(date +'%d%m%y')
    - name: Aiguilleur - Install dependencies
      run: |
        cd ./aiguilleur
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Aiguilleur - Test with pytest
      run: |
        cd ./aiguilleur
        pytest ./app.py
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Aiguilleur - Build the Docker image
      run:  |
        cd ./aiguilleur
        docker build . --file Dockerfile --tag gregorie/isla-aiguilleur:$(date +'%d%m%y')
        docker push gregorie/isla-aiguilleur:$(date +'%d%m%y')
    - name: Controleur Utilisateur - Install dependencies
      run: |
        cd ./controleur_db
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Controleur Utilisateur - Build the Docker image
      run:  |
        cd ./aiguilleur
        docker build . --file Dockerfile --tag gregorie/isla-controleur_db:$(date +'%d%m%y')
        docker push gregorie/isla-controleur_db:$(date +'%d%m%y')
